name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: |
          docker build -t cyprienderuelle/cd:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push cyprienderuelle/cd:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 8022
          script: |
            docker pull cyprienderuelle/cd:latest
            docker stop cd || true
            docker rm cd || true
            docker run -d --name cd -p 80:80 cyprienderuelle/cd:latest
